dax name: <nucleosome>
files:
   file: <heatsystem.1.mdin>
      pfn: <file://.*/target/nucleosome/work/outputs/heatsystem.1.mdin>
   file: <heatsystem.2.mdin>
      pfn: <file://.*/target/nucleosome/work/outputs/heatsystem.2.mdin>
   file: <minimization.mdin>
      pfn: <file://.*/target/nucleosome/work/outputs/minimization.mdin>
   file: <prmtop>
      pfn: <file://.*/target/nucleosome/work/outputs/prmtop>
   file: <restart.1>
      pfn: <file://.*/target/nucleosome/work/outputs/restart.1>
   file: <restart.2>
      pfn: <file://.*/target/nucleosome/work/outputs/restart.2>
   file: <restart.min>
      pfn: <file://.*/target/nucleosome/work/outputs/restart.min>
jobs:
   job: <dynamics-1>, id: <1n5> namespace: <nucleosome> version: <1.0>
      usedfile: <dyn1.out>
      usedfile: <heatsystem.1.mdin>
      usedfile: <logfile>
      usedfile: <prmtop>
      usedfile: <restart.1>
      usedfile: <restrt>
         profile: namespace:<globus> key:<host_xcount> value:<...>
         profile: namespace:<globus> key:<jobType> value:<...>
         profile: namespace:<globus> key:<maxWallTime> value:<...>
         profile: namespace:<globus> key:<queue> value:<...>
         profile: namespace:<globus> key:<xcount> value:<...>
   job: <dynamics-2>, id: <1n6> namespace: <nucleosome> version: <1.0>
      usedfile: <dyn2.out>
      usedfile: <heatsystem.2.mdin>
      usedfile: <logfile>
      usedfile: <prmtop>
      usedfile: <restart.2>
      usedfile: <restrt>
         profile: namespace:<globus> key:<host_xcount> value:<...>
         profile: namespace:<globus> key:<jobType> value:<...>
         profile: namespace:<globus> key:<maxWallTime> value:<...>
         profile: namespace:<globus> key:<queue> value:<...>
         profile: namespace:<globus> key:<xcount> value:<...>
   job: <minimization>, id: <1n2> namespace: <nucleosome> version: <1.0>
      usedfile: <logfile>
      usedfile: <min.out>
      usedfile: <minimization.mdin>
      usedfile: <prmtop>
      usedfile: <restart.min>
      usedfile: <restrt>
         profile: namespace:<globus> key:<host_xcount> value:<...>
         profile: namespace:<globus> key:<jobType> value:<...>
         profile: namespace:<globus> key:<maxWallTime> value:<...>
         profile: namespace:<globus> key:<xcount> value:<...>
transformations:
executables:
   executable: <dynamics-1> namespace: <nucleosome>, version: <1.0>, arch: <x86_64>, os: <linux>
      pfn: <file:///home/scox/gpu/bin/pmemd.cuda.MPI>
   executable: <dynamics-2> namespace: <nucleosome>, version: <1.0>, arch: <x86_64>, os: <linux>
      pfn: <file:///home/scox/gpu/bin/pmemd.cuda.MPI>
   executable: <minimization> namespace: <nucleosome>, version: <1.0>, arch: <x86_64>, os: <linux>
      pfn: <file:///home/scox/gpu/bin/pmemd.MPI>
dependencies:
   dependency: <1n5>
      parent: parent=><minimization> edge_label=><None>
   dependency: <1n6>
      parent: parent=><dynamics-1> edge_label=><None>