dax name: <nucleosome>
files:
jobs:
   job: <dynamics-1>, id: <1n5> namespace: <nucleosome> version: <1.0>
         profile: namespace:<globus> key:<host_xcount> value:<...>
         profile: namespace:<globus> key:<jobType> value:<...>
         profile: namespace:<globus> key:<maxWallTime> value:<...>
         profile: namespace:<globus> key:<queue> value:<...>
         profile: namespace:<globus> key:<xcount> value:<...>
   job: <dynamics-2>, id: <1n6> namespace: <nucleosome> version: <1.0>
         profile: namespace:<globus> key:<host_xcount> value:<...>
         profile: namespace:<globus> key:<jobType> value:<...>
         profile: namespace:<globus> key:<maxWallTime> value:<...>
         profile: namespace:<globus> key:<queue> value:<...>
         profile: namespace:<globus> key:<xcount> value:<...>
   job: <minimization>, id: <1n2> namespace: <nucleosome> version: <1.0>
         profile: namespace:<globus> key:<host_xcount> value:<...>
         profile: namespace:<globus> key:<jobType> value:<...>
         profile: namespace:<globus> key:<maxWallTime> value:<...>
         profile: namespace:<globus> key:<xcount> value:<...>
transformations:
executables:
dependencies:
   dependency: <1n5>
      parent: parent=><minimization> edge_label=><None>
   dependency: <1n6>
      parent: parent=><dynamics-1> edge_label=><None>