#!/bin/bash

set -e
set +x

mode=$1
shift

output_dax=padcswan-uber.dax
output_dir=$(pwd)/daxen-$mode

rm -rf $output_dir *.dax *.xml *.rc *.tc *.log *.properties

if [ ! -f "model/$mode-context.graphml" ]; then
    echo "error: model/$mode-context.graphml does not exist"
fi

sites=local
if [ "x$mode" == "xblueridge" -o "x$mode" == "xblueridge-largememory" ]; then
    sites=local,RENCI-Blueridge
elif [ "x$mode" == "xnersc-carver" ]; then
    sites=local,NERSC-Carver
elif [ "x$mode" == "osg-engage" ]; then
    sites=local,OSG-Engage
fi

set -x
graysonc                                                                    \
    --model=$GRAYSON_HOME/samples/padcswan/model/$mode-context.graphml      \
    --modelpath="$GRAYSON_HOME/samples:model"                               \
    --define='data=data'                                                    \
    --loglevel=debug                                                        \
    --directory=$output_dir                                                 \
    --output=$output_dax                                                    \
    --sites=$sites                                                          \
    $*  > log.txt 2>&1
set +x
mv log.txt $output_dir

launch_time=$(date)
watch_cmd=$(grep 'pegasus-status' $output_dir/log.txt | sed -e 's,.*   ,,')
if [ ! -z "$watch_cmd" ]; then
    watch -n 10 "
                 echo ==================================================================================================================================================
                 echo == Grayson Workflow
                 echo ==================================================================================================================================================
                 echo == launch-time: [$launch_time]
                 echo ==         dax: [$output_dir/$output_dax] 
                 echo ==   watch cmd: [$watch_cmd]
                 echo ==================================================================================================================================================
                 $watch_cmd"
fi

