<?xml version="1.0" encoding="UTF-8"?>
<!-- generated: 2011-05-12 18:22:16.462658 -->
<!-- generator: python -->
<adag xmlns="http://pegasus.isi.edu/schema/DAX" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://pegasus.isi.edu/schema/DAX http://pegasus.isi.edu/schema/dax-3.2.xsd" version="3.2" name="grayson-test">

	<!-- part 1: Replica catalog (may be empty) -->
	<file name="data/data/input1">
		<pfn url="file:///home/scox/dev/grayson/web/data/data/input1" site="local"/>
	</file>
	<executable name="job1" namespace="grayson-test" version="2.0" arch="x86_64" os="linux" installed="false">
		<pfn url="file:///home/scox/dev/grayson/web/bin/sample" site="local"/>
	</executable>
	<executable name="job2" namespace="grayson-test" version="2.0" arch="x86_64" os="linux" installed="false">
		<pfn url="file:///home/scox/dev/grayson/web/bin/sample" site="local"/>
	</executable>

	<!-- part 2: Transformation catalog (may be empty) -->
	<transformation namespace="grayson-test" name="job1" version="2.0">
		<uses name="output-1"/>
		<uses name="job1"/>
		<uses name="job2.out"/>
	</transformation>
	<transformation namespace="grayson-test" name="job2" version="2.0">
		<uses name="output-2"/>
		<uses name="output-1"/>
		<uses name="job2"/>
	</transformation>
	<transformation namespace="grayson-test" name="job1" version="2.0">
		<uses name="data/data/input1"/>
		<uses name="job1.out"/>
		<uses name="job1"/>
	</transformation>
	<transformation namespace="grayson-test" name="job2" version="2.0">
		<uses name="job2.out"/>
		<uses name="job1.out"/>
		<uses name="job2"/>
	</transformation>

	<!-- part 3: Definition of all jobs/dags/daxes (at least one) -->
	<dax id="ID0000001" file="grayson-template.dax">
		<argument>-o <file name="job2.out"/></argument>
		<uses name="job2.out" link="output"/>
	</dax>
	<job id="ID0000002" namespace="grayson-test" name="job1" version="2.0">
		<argument>-i <file name="job2.out"/> -o <file name="output-1"/></argument>
		<uses name="job2.out" link="input"/>
		<uses name="output-1" link="output"/>
	</job>
	<job id="ID0000003" namespace="grayson-test" name="job2" version="2.0">
		<argument>-i <file name="output-1"/> -o <file name="output-2"/></argument>
		<uses name="output-1" link="input"/>
		<uses name="output-2" link="output"/>
	</job>
	<job id="ID0000004" namespace="grayson-test" name="job1" version="2.0">
		<argument>-i <file name="data/data/input1"/> -o <file name="job1.out"/></argument>
		<uses name="data/data/input1" link="input"/>
		<uses name="job1.out" link="output"/>
	</job>
	<job id="ID0000005" namespace="grayson-test" name="job2" version="2.0">
		<argument>-i <file name="job1.out"/> -o <file name="job2.out"/></argument>
		<uses name="job1.out" link="input"/>
		<uses name="job2.out" link="output"/>
	</job>

	<!-- part 4: List of control-flow dependencies (may be empty) -->
	<child ref="ID0000005">
		<parent ref="ID0000004"/>
	</child>
	<child ref="ID0000003">
		<parent ref="ID0000002"/>
	</child>
	<child ref="ID0000002">
		<parent ref="ID0000001"/>
	</child>
</adag>
