dax name: <blackdiamond>
files:
jobs:
   job: <analyze>, id: <1n5> namespace: <blackdiamond> version: <1.0>
   job: <findrange.1>, id: <1n2> namespace: <blackdiamond> version: <1.0>
   job: <findrange.2>, id: <1n3> namespace: <blackdiamond> version: <1.0>
   job: <preprocess>, id: <1n4> namespace: <blackdiamond> version: <1.0>
transformations:
executables:
dependencies:
   dependency: <1n2>
      parent: parent=><preprocess> edge_label=><None>
   dependency: <1n3>
      parent: parent=><preprocess> edge_label=><None>
   dependency: <1n5>
      parent: parent=><findrange.1> edge_label=><None>
   dependency: <1n5>
      parent: parent=><findrange.2> edge_label=><None>