dax name: <lambda-flow.20>
files:
   file: <c.22.tar.gz>
      pfn: <file://.*/samples/lambda/data/c.22.tar.gz>
   file: <input-one.tar.gz>
      pfn: <file://.*/work/outputs/input-one.tar.gz>
   file: <input-two.tar.gz>
      pfn: <file://.*/work/outputs/input-two.tar.gz>
jobs:
   job: <lambda>, id: <1n2> namespace: <lambda-flow.20> version: <1.0>
      usedfile: <c.22.tar.gz>
      usedfile: <c.22.tar.gz-5-out.tar.gz>
      usedfile: <c.22.tar.gz-6-out.tar.gz>
      usedfile: <input-one.tar.gz>
      usedfile: <input-two.tar.gz>
   dax-job: <quality-check.20.dax>
      usedfile: <c.22.tar.gz-6-out.tar.gz>
transformations:
executables:
   executable: <lambda> namespace: <lambda-flow.20>, version: <1.0>, arch: <x86_64>, os: <linux>
      pfn: <file://.*/bin/lambda.sh>
dependencies:
   dependency: <ID0000001>
      parent: parent=><lambda> edge_label=><None>