dax name: <scan-uber>
files:
jobs:
   job: <map>, id: <1n12_synth> namespace: <scan-uber> version: <1.0>
         profile: namespace:<env> key:<CONDOR_HOME> value:<...>
         profile: namespace:<env> key:<GLOBUS_LOCATION> value:<...>
         profile: namespace:<env> key:<GRAYSON_HOME> value:<...>
         profile: namespace:<env> key:<LD_LIBRARY_PATH> value:<...>
         profile: namespace:<env> key:<PATH> value:<...>
         profile: namespace:<env> key:<PYTHONPATH> value:<...>
   job: <prepare>, id: <1n9> namespace: <scan-uber> version: <1.0>
   job: <reduce>, id: <1n10> namespace: <scan-uber> version: <1.0>
   dax-job: <scan-flow.dax>
   job: <score>, id: <1n2> namespace: <scan-uber> version: <1.0>
transformations:
executables:
dependencies:
   dependency: <1n10>
      parent: parent=><scan-flow.dax> edge_label=><None>
   dependency: <1n12_synth>
      parent: parent=><prepare> edge_label=><None>
   dependency: <1n2>
      parent: parent=><reduce> edge_label=><None>
   dependency: <ID0000001>
      parent: parent=><prepare> edge_label=><None>
   dependency: <ID0000001>
      parent: parent=><map> edge_label=><None>