#!/bin/bash

set -e
set +x

mode=$1
shift

output_dax=delta-uber.dax
output_dir=$(pwd)/daxen-$mode

rm -rf $output_dir *.dax *.xml *.rc *.tc *.log *.properties

set -x
graysonc                                                                    \
    --model=$PWD/model/$mode-context.graphml                                \
    --modelpath="$GRAYSON_HOME/samples:$PWD/model"                          \
    --define='file=x'                                                       \
    --loglevel=debug                                                        \
    --output=$output_dax                                                    \
    --package                                                               \
    --package-file=bin                                                      \
    --package-file=model                                                    \
    $*  > log.txt 2>&1
set +x
tail -100 log.txt


