#!/bin/bash

set -e
set +x

mode=$1
shift

output_dax=scan-uber.dax
output_dir=$(pwd)/daxen-$mode

rm -rf $output_dir *.dax *.xml *.rc *.tc *.log *.properties

set -x
graysonc                                                                    \
    --model=$GRAYSON_HOME/samples/scan/model/$mode-context.graphml      \
    --modelpath="$GRAYSON_HOME/samples:model"                               \
    --loglevel=debug                                                        \
    --directory=$output_dir                                                 \
    --output=$output_dax                                                    \
    $*  > log.txt 2>&1
if [ $? -ne 0 ]; then
    cat log.txt
fi
set +x

mv log.txt $output_dir

launch_time=$(date)
watch_cmd=$(grep 'pegasus-status' $output_dir/log.txt | sed -e 's,.*   ,,')
if [ ! -z "$watch_cmd" ]; then
    watch -n 5 "
                 echo ==================================================================================================================================================
                 echo == Grayson Workflow
                 echo ==================================================================================================================================================
                 echo == launch-time: [$launch_time]
                 echo ==         dax: [$output_dir/$output_dax] 
                 echo ==   watch cmd: [$watch_cmd]
                 echo ==================================================================================================================================================
                 $watch_cmd"
fi

